### ISSUE TITLE
required step

### ISSUE THREAD

**Issue by Flaze07** [MC874/MCrev#1]
please add this step to the how to use 
deletion of the appxblockmap, appxsignature files. 
Because if the 2 files still exist, it won't successfully sideload the minecraft

**Comment by MC874** [comment]
Hi!
Current MCrev only supports Minecraft Windows 10 Mod that made by me wich it has certificate. The Installer of MCrev 1.8 will install custom certificate in order to Install Minecraft. For newer version of Minecraft, i have separated installer included inside the Minecraft Windows 10 zip. 

Altough, this feature for sideloading already implemented in MCrev 1.17 for future releases. I havent update anything on github for a while but you can check my Youtube channel for newer version of MCrev. What you found here is older and deprecated releases of MCrev.
-Thanks

**Comment by Iemand005** [comment]
This is just the 2018 FH3 Codex crack...
What are the exe files for? it doesn't fix the system on 21H2, it executes some scripts. 3 years ago this all wasn't needed in order to have it work. The online crack is way better than this, even the ClipSVC mod works better.

**Comment by MC874** [comment]
> 

The repository is indeed for Windows 10 19H and way-back. Check for the new releases, its the updated one. Its already combining all the possible bypass, including disabling ClipSVC service, Registry, Windows Store DLL, Preventing Runtime Broker to run while in-game.

**Comment by MC874** [comment]
Closing Issue as its resolved
